# Generated by Django 4.1.4 on 2022-12-15 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adan', '0002_state_prayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='offset_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PrayerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('after', 'after'), ('before', 'before')], max_length=50)),
                ('repeated', models.BooleanField(default=True)),
                ('prayer', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
