# Generated by Django 4.1.4 on 2022-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0003_state_offset_time_prayerevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='prayer_time',
            field=models.JSONField(blank=True, null=True, verbose_name='prayer data time'),
        ),
    ]
