# Generated by Django 4.1.4 on 2022-12-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0004_alter_prayer_prayer_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of mosque')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='liveevent',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
