# Generated by Django 4.1.4 on 2022-12-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0006_mosque_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='prayer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adan.state'),
        ),
    ]
