# Generated by Django 4.1.4 on 2022-12-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0007_mosque_prayer_mosque_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerevent',
            name='prayer',
            field=models.CharField(choices=[('elfajer', 'elfajer'), ('duhr', 'duhr'), ('alasr', 'alasr'), ('almaghreb', 'almaghreb'), ('alaicha', 'alaicha')], max_length=50),
        ),
    ]
