# Generated by Django 4.1.4 on 2022-12-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0010_rename_user_mosque_topic_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='', verbose_name='audio file')),
                ('prayer', models.CharField(choices=[('elfajer', 'elfajer'), ('duhr', 'duhr'), ('alasr', 'alasr'), ('almaghreb', 'almaghreb'), ('alaicha', 'alaicha')], max_length=50)),
            ],
        ),
    ]
