# Generated by Django 4.1.4 on 2022-12-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0012_prayeraudio_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayerevent',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
