# Generated by Django 4.1.4 on 2022-12-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0013_liveevent_audio_duration_prayerevent_audio_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque',
            name='prayer',
        ),
        migrations.AddField(
            model_name='state',
            name='prayer_time',
            field=models.JSONField(blank=True, null=True, verbose_name='prayer data time'),
        ),
        migrations.DeleteModel(
            name='Prayer',
        ),
    ]
