# Generated by Django 4.1.4 on 2022-12-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0014_remove_mosque_prayer_state_prayer_time_delete_prayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='mosque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adan.mosque'),
        ),
    ]
