# Generated by Django 4.1.4 on 2022-12-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0016_remove_liveevent_mosque_liveevent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
