# Generated by Django 4.1.4 on 2022-12-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0018_prayeraudio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerevent',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
