# Generated by Django 4.1.4 on 2022-12-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0019_prayerevent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayeraudio',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
