# Generated by Django 4.1.4 on 2023-01-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0021_alter_mosque_topic_alter_topic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='name of mosque'),
        ),
    ]
