# Generated by Django 4.1.4 on 2023-01-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0022_alter_mosque_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque',
            name='state',
        ),
        migrations.AddField(
            model_name='topic',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adan.state'),
        ),
    ]
