# Generated by Django 4.1.4 on 2023-01-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0023_remove_mosque_state_topic_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerevent',
            name='repeated',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
