# Generated by Django 4.1.4 on 2023-01-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0024_alter_prayerevent_repeated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayerevent',
            name='repeated',
        ),
    ]
