# Generated by Django 4.1.4 on 2023-01-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0025_remove_prayerevent_repeated'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adan.state'),
        ),
    ]
