# Generated by Django 4.1.4 on 2023-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0026_mosque_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='state',
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
