# Generated by Django 4.1.4 on 2023-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0027_remove_topic_state_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerevent',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
