# Generated by Django 4.1.4 on 2023-01-25 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0029_state_prayer_time_am_pm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='prayer_time_am_pm',
            field=models.JSONField(blank=True, null=True, verbose_name='prayer data time with am pm'),
        ),
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adan.topic')),
            ],
        ),
    ]
