# Generated by Django 4.1.4 on 2023-01-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0030_alter_state_prayer_time_am_pm_plug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plug',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adan.mosque'),
        ),
    ]
