# Generated by Django 4.1.4 on 2023-02-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0031_alter_plug_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='speaker_status',
            field=models.BooleanField(default=False, help_text='speaker status'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='status',
            field=models.BooleanField(default=False, help_text='raspbery pi status'),
        ),
    ]
